e2e tests for enter latest release info, enter local police info and date and time of the recall request received from probation service,
ministryofjustice/manage-recalls-e2e-tests pull request #28
Opened 2021-08-10 16:42 UTC by shahnaazr

e2e tests for 
1. enter latest release info, 
2. enter local police info 
3. date and time of the recall request received from probation service

https://dsdmoj.atlassian.net/browse/PUD-317
https://dsdmoj.atlassian.net/browse/PUD-248
https://dsdmoj.atlassian.net/browse/PUD-253

2021-08-11 08:27 UTC, philsegal commented on src/test/resources/features/managerecalls/ManageRecall.feature
> +    And Maria submits the police contact details
We should have a test/step where we are validating that the values entered are being stored.

2021-08-11 08:38 UTC, shahnaazr commented on src/test/resources/features/managerecalls/ManageRecall.feature
> +    And Maria submits the police contact details
I presume that would be done in the lower level test. Happy to discuss thou.

2021-08-11 12:57 UTC, shahnaazr commented on src/test/resources/features/managerecalls/ManageRecall.feature
> +    And Maria submits the police contact details
validation added as agreed

2021-08-11 13:02 UTC, philsegal approved these changes
Thankyou :)

2021-08-11 15:02 UTC, philsegal commented on src/test/java/cucumber/steps/NavigationSteps.java
> +        userEnters(customer, RecallReceivedPage.HOUR_FIELD, "33");
You cant have an hour of 33.

2021-08-11 15:03 UTC, philsegal commented on src/test/java/cucumber/steps/NavigationSteps.java
> +        userEnters(customer, RecallReceivedPage.HOUR_FIELD, "33");
Should be `15:33` to match the assertion

2021-08-11 15:03 UTC, philsegal requested changes
Fix the hour/minute to be valid and match the assertion

2021-08-12 08:01 UTC, philsegal commented on src/test/java/cucumber/steps/NavigationSteps.java
> +        //  FIXME - The following validation is temp disabled due to the UI Bug https://dsdmoj.atlassian.net/browse/PUD-379
Rather than disabling the logic, can we extract it to a new step and run it only for the "Book a recall" feature?

2021-08-12 08:02 UTC, philsegal commented on src/test/resources/features/managerecalls/ManageRecall.feature
> +    And Maria is able to see the details submitted earlier
👍

2021-08-12 08:02 UTC, philsegal commented on src/test/java/cucumber/pages/DecisionOnRecallRecommendationPage.java
> +    public static final Target CONTINUE_BUTTON = getTargetByDataQa("continueButton");
This line can be extracted to the `PpudPage` class across all pages. saves repeating it everywhere

2021-08-12 09:48 UTC, philsegal approved these changes
Will refactor as part of next ticket

2021-08-12 09:48 UTC, merged